on:
  push:

jobs:

  # When you push to a branch, we cancel previous runs of jobs in this file on that branch.
  cancel:
    name: 'Cancel previous runs on branch'
    # if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    # timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  update_lean_xyz_branch_and_build:
    runs-on: ubuntu-latest
    name: Update lean-x.y.z branch and build project
    steps:

    - name: checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: update branch
      if: github.ref == 'refs/heads/master'
      uses: leanprover-contrib/update-versions-action@master

    - name: build project
      uses: leanprover-contrib/lean-build-action@master

  lint:
    name: Lint  zsqrt2_eucl
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: retrieve build
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.artifact_name }}

      - name: untar build
        run: tar -xf workspace.tar

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: lint
        # Uncomment the following line to make the build succeed even if there are linting errors
        # continue-on-error: true
        run: |
          ./scripts/mk_all.sh
          lean --run scripts/lint_project.lean